---
- name: Install Docker and Run Juice Shop Containers
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Install pip3
      apt:
        name: python3-pip
        state: present

    - name: Upgrade pip3
      pip:
        name: pip
        executable: pip3
        state: latest

    - name: Install Docker SDK library
      pip:
        name: docker
        state: present
        executable: pip3

    # - name: Pull Juice Shop Docker image
    #   docker_image:
    #     name: bkimminich/juice-shop
    #     state: present

    - name: Run Juice Shop containers
      docker_container:
        name: juice-shop-{{ item }}
        image: bkimminich/juice-shop
        ports:
          - "{{ 1000 + item }}:3000"
        state: started
      loop: "{{ range(1, 16) | list }}"
      loop_control:
        index_var: item

